import React, { useState } from 'react';
import { Video, Bolt, Copy, Check, Download, Image as ImageIcon, Sparkles, RefreshCw, Film, Wand2, Play } from 'lucide-react';
import { CreatorPlan, ScriptScene } from '../types';

interface Stage3Props {
  plan: CreatorPlan;
  onRegenerateScript: () => void;
  onGenerateSceneVisual: (sceneId: string, type?: 'image' | 'video') => void;
  isGenerating?: boolean;
  onShowToast: (msg: string) => void;
}

export const Stage3ScriptGeneration: React.FC<Stage3Props> = ({
  plan,
  onRegenerateScript,
  onGenerateSceneVisual,
  isGenerating,
  onShowToast,
}) => {
  const [copiedHookIndex, setCopiedHookIndex] = useState<number | null>(null);
  const [copiedFullScript, setCopiedFullScript] = useState(false);
  const [selectedHook, setSelectedHook] = useState<string>(plan.hookPhrases[0] || '');

  // Copy single hook
  const handleCopyHook = (hookText: string, index: number) => {
    navigator.clipboard.writeText(hookText);
    setCopiedHookIndex(index);
    setSelectedHook(hookText);
    onShowToast(`후킹 문구가 복사되었습니다: "${hookText.slice(0, 15)}..."`);
    setTimeout(() => setCopiedHookIndex(null), 2000);
  };

  // Copy full script
  const handleCopyFullScript = () => {
    const fullText = `[영상 제목]: ${plan.recommendedTitle}\n\n[도입부 후킹 문구]: ${selectedHook}\n\n` +
      plan.scenes.map(s => `[Scene ${s.sceneNumber} - ${s.sceneTitle} (${s.timeRange})]\n${s.scriptText}\n자막/모션: ${s.textOverlay}\n`).join('\n');
    
    navigator.clipboard.writeText(fullText);
    setCopiedFullScript(true);
    onShowToast('전체 영상 대본이 클립보드에 복사되었습니다!');
    setTimeout(() => setCopiedFullScript(false), 2000);
  };

  // Download script file
  const handleDownloadScript = () => {
    const fullText = `====================================\nCreator Hub AI - 영상 제작 대본\n====================================\n\n` +
      `영상 제목: ${plan.recommendedTitle}\n` +
      `키워드: ${plan.keyword}\n` +
      `예상 조회수: ${plan.estimatedViews} | 예상 분량: ${plan.totalDuration}\n\n` +
      `------------------------------------\n[필살기 후킹 문구 (첫 3초)]\n${selectedHook}\n\n` +
      `------------------------------------\n[장면별 대본 및 시각 가이드]\n` +
      plan.scenes.map(s => `\n[Scene ${s.sceneNumber}: ${s.sceneTitle} (${s.timeRange})]\n- 대본: ${s.scriptText}\n- 자막 오버레이: ${s.textOverlay}\n- 연출 프롬프트: ${s.imagePrompt}\n`).join('') +
      `\n====================================\nGenerated by Creator Hub AI`;

    const blob = new Blob([fullText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `대본_${plan.recommendedTitle.slice(0, 15)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    onShowToast('대본 파일이 (.txt) 성공적으로 다운로드되었습니다.');
  };

  return (
    <section className="flex-1 flex flex-col gap-4 min-w-[460px] max-w-[640px]">
      {/* Stage Header */}
      <div className="flex items-center justify-between px-1">
        <h2 className="text-sm font-bold text-gray-900 flex items-center gap-2 font-['Montserrat']">
          <Video className="w-4 h-4 text-[#6200ee]" />
          Script & AI Assets
        </h2>
        <span className="text-[10px] font-bold tracking-wider text-gray-500 bg-gray-200/60 px-2 py-0.5 rounded">
          STAGE 3
        </span>
      </div>

      {/* Main Container */}
      <div className="bg-white p-5 rounded-2xl shadow-xs border border-gray-200/80 flex-1 flex flex-col">
        {/* Title and regenerate button */}
        <div className="flex items-center justify-between mb-3">
          <div>
            <h3 className="text-xs font-bold text-[#4800b2] uppercase tracking-wide">
              숏폼 특화 대본 (Scene-by-Scene)
            </h3>
            <p className="text-[11px] text-gray-500">
              버튼 한 번에 생성되는 완성형 영상 시나리오
            </p>
          </div>
          <button
            onClick={onRegenerateScript}
            disabled={isGenerating}
            className="px-3 py-1.5 bg-gradient-to-r from-[#6200ee] to-[#4800b2] text-white text-xs font-bold rounded-xl shadow-xs hover:shadow-md transition-all flex items-center gap-1.5"
          >
            {isGenerating ? (
              <RefreshCw className="w-3.5 h-3.5 animate-spin" />
            ) : (
              <Bolt className="w-3.5 h-3.5 text-yellow-300 fill-yellow-300" />
            )}
            <span>대본 재생성</span>
          </button>
        </div>

        {/* 필살기 후킹 문구 (Top 3초 hook sentence selector) */}
        <div className="bg-purple-50/80 p-3.5 rounded-xl border-l-4 border-[#6200ee] border-t border-r border-b border-purple-100 mb-3">
          <div className="flex items-center justify-between mb-1.5">
            <span className="text-[11px] font-extrabold text-[#4800b2] uppercase tracking-wider flex items-center gap-1">
              <Sparkles className="w-3.5 h-3.5 text-[#6200ee]" />
              필살기 후킹 문구 (시청자 사로잡는 첫 3초)
            </span>
            <span className="text-[10px] text-purple-700 bg-purple-100 px-2 py-0.5 rounded font-bold">
              AI 추천
            </span>
          </div>

          {/* List of 3~5 hook phrases */}
          <div className="space-y-1.5 max-h-[120px] overflow-y-auto custom-scrollbar pr-1">
            {plan.hookPhrases.map((hook, idx) => {
              const isSelected = selectedHook === hook;
              return (
                <div
                  key={idx}
                  onClick={() => setSelectedHook(hook)}
                  className={`p-2 rounded-lg text-xs font-bold flex items-center justify-between transition-all cursor-pointer ${
                    isSelected
                      ? 'bg-white text-[#4800b2] border border-purple-300 shadow-2xs'
                      : 'bg-purple-100/50 text-gray-700 hover:bg-white'
                  }`}
                >
                  <span className="line-clamp-1 italic">
                    "{hook}"
                  </span>
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      handleCopyHook(hook, idx);
                    }}
                    className="p-1 hover:bg-purple-100 rounded text-purple-600 transition-colors shrink-0 ml-2"
                    title="후킹 문구 복사"
                  >
                    {copiedHookIndex === idx ? (
                      <Check className="w-3.5 h-3.5 text-green-600" />
                    ) : (
                      <Copy className="w-3.5 h-3.5" />
                    )}
                  </button>
                </div>
              );
            })}
          </div>
        </div>


        {/* Scene-by-Scene Breakdowns */}
        <div className="space-y-4 flex-1 overflow-y-auto min-h-[380px] max-h-[580px] pr-1.5 custom-scrollbar">
          {plan.scenes.map((scene: ScriptScene) => (
            <div
              key={scene.id}
              className="bg-gray-50/90 rounded-2xl p-4 border border-gray-200 hover:border-purple-300 transition-all shadow-xs"
            >
              {/* Scene Title & Time Header */}
              <div className="flex justify-between items-center mb-2">
                <span className="font-extrabold text-[#4800b2] text-xs flex items-center gap-1.5">
                  <Film className="w-4 h-4 text-[#6200ee]" />
                  Scene {scene.sceneNumber}: {scene.sceneTitle}
                </span>
                <span className="text-[10px] font-bold text-gray-600 bg-gray-200/80 px-2.5 py-0.5 rounded-full">
                  {scene.timeRange}
                </span>
              </div>

              {/* Script Text */}
              <p className="text-xs text-gray-800 leading-relaxed mb-3 font-medium bg-white p-3 rounded-xl border border-gray-100 shadow-2xs">
                "{scene.scriptText}"
              </p>

              {/* Subtitle Overlay Guide */}
              <div className="bg-purple-50 p-2.5 rounded-xl mb-3 flex items-center gap-2 border border-purple-100 text-[11px] text-[#4800b2] font-semibold">
                <Sparkles className="w-3.5 h-3.5 shrink-0 text-[#6200ee]" />
                <span className="line-clamp-1">
                  자막 오버레이: {scene.textOverlay}
                </span>
              </div>

              {/* Large Prominent Scene Visual Preview Canvas */}
              <div className="space-y-2">
                <div className="relative w-full aspect-video rounded-xl overflow-hidden border-2 border-purple-200/80 shadow-md bg-slate-900 group">
                  {scene.generatedImageUrl ? (
                    <img
                      src={scene.generatedImageUrl}
                      alt={`Scene ${scene.sceneNumber} visual`}
                      className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"
                      referrerPolicy="no-referrer"
                    />
                  ) : (
                    <div className="w-full h-full flex flex-col items-center justify-center text-gray-400 p-4 text-center bg-slate-800">
                      <ImageIcon className="w-8 h-8 mb-1.5 text-purple-400/80" />
                      <p className="text-xs font-bold text-gray-300">AI 시각 자료 미생성</p>
                      <p className="text-[10px] text-gray-400">아래 버튼으로 고화질 이미지나 비디오 에셋을 즉시 창작하세요</p>
                    </div>
                  )}

                  {/* Top Media Type Badge */}
                  <div className="absolute top-2.5 left-2.5 flex items-center gap-1.5">
                    {scene.mediaType === 'video' ? (
                      <span className="bg-black/80 backdrop-blur-md text-yellow-300 text-[10px] font-extrabold px-2.5 py-1 rounded-md shadow-md flex items-center gap-1 border border-yellow-400/30">
                        <Video className="w-3 h-3 text-yellow-300" />
                        AI Video Motion (60fps)
                      </span>
                    ) : (
                      <span className="bg-black/80 backdrop-blur-md text-purple-300 text-[10px] font-extrabold px-2.5 py-1 rounded-md shadow-md flex items-center gap-1 border border-purple-400/30">
                        <ImageIcon className="w-3 h-3 text-purple-300" />
                        AI Image Asset
                      </span>
                    )}
                  </div>

                  {/* Subtitle Overlay Preview on top of media */}
                  {scene.generatedImageUrl && (
                    <div className="absolute bottom-2 left-2 right-2 bg-black/75 backdrop-blur-xs text-white text-[11px] font-black text-center py-1.5 px-2 rounded-lg border border-white/20 shadow-lg">
                      {scene.textOverlay}
                    </div>
                  )}

                  {/* Loading Overlay */}
                  {scene.isGeneratingImage && (
                    <div className="absolute inset-0 bg-slate-950/80 backdrop-blur-xs flex flex-col items-center justify-center text-white p-4">
                      <RefreshCw className="w-7 h-7 text-purple-400 animate-spin mb-2" />
                      <p className="text-xs font-bold text-purple-200">Gemini AI 시각 에셋 렌더링 중...</p>
                      <p className="text-[10px] text-gray-400 mt-1">프롬프트 가공 및 실시간 화질 업스케일링</p>
                    </div>
                  )}
                </div>

                {/* English Prompt Info Box */}
                <div className="bg-white p-2.5 rounded-xl border border-gray-200 text-[10px] flex items-center justify-between gap-2">
                  <div className="flex items-center gap-1.5 overflow-hidden">
                    <Wand2 className="w-3.5 h-3.5 text-[#6200ee] shrink-0" />
                    <span className="font-mono text-gray-600 truncate" title={scene.imagePrompt}>
                      Prompt: {scene.imagePrompt}
                    </span>
                  </div>
                  <button
                    onClick={() => {
                      navigator.clipboard.writeText(scene.imagePrompt);
                      onShowToast('프롬프트가 복사되었습니다!');
                    }}
                    className="p-1 hover:bg-purple-50 text-purple-600 rounded shrink-0 transition-colors"
                    title="프롬프트 복사"
                  >
                    <Copy className="w-3.5 h-3.5" />
                  </button>
                </div>

                {/* Dedicated Action Buttons Row with Icons */}
                <div className="grid grid-cols-2 gap-2 pt-1">
                  <button
                    onClick={() => onGenerateSceneVisual(scene.id, 'image')}
                    disabled={scene.isGeneratingImage}
                    className="py-2 px-3 bg-purple-50 hover:bg-purple-100 border border-purple-200 text-[#4800b2] text-xs font-bold rounded-xl transition-all flex items-center justify-center gap-1.5 shadow-2xs hover:shadow-xs active:scale-95"
                  >
                    <ImageIcon className="w-3.5 h-3.5 text-[#6200ee]" />
                    <span>AI 이미지 생성</span>
                  </button>

                  <button
                    onClick={() => onGenerateSceneVisual(scene.id, 'video')}
                    disabled={scene.isGeneratingImage}
                    className="py-2 px-3 bg-gradient-to-r from-[#6200ee] to-[#4800b2] hover:from-[#5300cd] hover:to-[#38008c] text-white text-xs font-bold rounded-xl transition-all flex items-center justify-center gap-1.5 shadow-2xs hover:shadow-xs active:scale-95"
                  >
                    <Video className="w-3.5 h-3.5 text-yellow-300" />
                    <span>AI 비디오 생성</span>
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Copy & Download Buttons */}
        <div className="mt-3 pt-3 border-t border-gray-200 flex gap-2">
          <button
            onClick={handleCopyFullScript}
            className="flex-1 py-2.5 bg-gray-100 hover:bg-gray-200 text-gray-800 text-xs font-bold rounded-xl transition-colors flex items-center justify-center gap-1.5"
          >
            {copiedFullScript ? (
              <Check className="w-4 h-4 text-green-600" />
            ) : (
              <Copy className="w-4 h-4 text-gray-600" />
            )}
            <span>대본 전체 복사</span>
          </button>

          <button
            onClick={handleDownloadScript}
            className="flex-1 py-2.5 bg-[#6200ee] hover:bg-[#5300cd] text-white text-xs font-bold rounded-xl transition-colors flex items-center justify-center gap-1.5 shadow-xs"
          >
            <Download className="w-4 h-4" />
            <span>대본 저장 (.txt)</span>
          </button>
        </div>
      </div>
    </section>
  );
};
